##############################
# Create final image         #
##############################

FROM localhost/builder:0.1 as builder
FROM localhost/cuda-runtime:0.1

ARG PYTHON=python3.11
ENV PYTHON="${PYTHON}" \
    APP_ROOT="/opt/app-root" \
    VIRTUAL_ENV="${APP_ROOT}" \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_COMPILE=1 \
    PS1="(app-root) \w\$ "

COPY --from=builder --chown=1001:0 ${VIRTUAL_ENV} ${VIRTUAL_ENV}

USER 1001

WORKDIR /opt/app-root/bin

# Copy packages list
COPY --chown=1001:0 requirements-jupyter.txt ./

# Copy notebook launcher and utils
COPY --chown=1001:0 utils utils/
COPY --chown=1001:0 start-notebook.sh ./

# Install packages and cleanup
# (all commands are chained to minimize layer size)
RUN echo "Installing softwares and packages" && \
    # Install Python packages \
    pip install --no-cache-dir -r requirements-jupyter.txt && \
    rm -f ./requirements-jupyter.txt && \
    # Replace Notebook's launcher, "(ipykernel)" with Python's version 3.x.y \
    sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json 
    # Fix permissions to support pip in Openshift environments \
    # chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    # fix-permissions /opt/app-root -P

# Jupyter Server config to allow hidden files/folders in explorer. Ref: https://jupyterlab.readthedocs.io/en/latest/user/files.html#displaying-hidden-files
# Jupyter Lab config to hide disabled exporters (WebPDF, Qtpdf, Qtpng)
COPY --chown=1001:0 etc/ /opt/app-root/etc/jupyter/

WORKDIR /opt/app-root/src

ENTRYPOINT ["start-notebook.sh"]