FROM localhost/cuda-devel:0.1 AS builder

# InstructLab version
ARG GIT_TAG=v0.18.4

USER 0

RUN dnf install -y libcudnn8 nvidia-driver-NVML nvidia-driver-cuda-libs && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*

USER 1001

RUN python3.11 -m pip install --force-reinstall nvidia-cuda-nvcc-cu12

RUN export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64" \
    && export CUDA_HOME=/usr/local/cuda \
    && export PATH="/usr/local/cuda/bin:$PATH" \
    && export XLA_TARGET=cuda120 \
    && export XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/local/cuda

RUN if [[ "$(uname -m)" != "aarch64" ]]; then export CFLAGS="-mno-avx"; fi && \
    CMAKE_ARGS="-DLLAMA_CUBLAS=on" python3.11 -m pip install -r https://raw.githubusercontent.com/instructlab/instructlab/${GIT_TAG}/requirements.txt --force-reinstall --no-cache-dir llama-cpp-python
RUN python3.11 -m pip install git+https://github.com/instructlab/instructlab.git@${GIT_TAG}
